In [2]:
import sys
import tensorflow as tf
sys.path.append('../../generative-adversarial-nets/')
from ganetwork import GAN, CGAN
from sklearn import datasets
from sklearn.preprocessing import minmax_scale, LabelBinarizer

In [4]:
ds = datasets.load_iris()
X, y = minmax_scale(ds.data), LabelBinarizer().fit_transform(ds.target)

In [3]:
discriminator_layers=[(4, None), (6, tf.nn.tanh), (3, tf.nn.tanh), (1, None)]
generator_layers=[(6, None), (8, tf.nn.tanh), (4, None)]
gan = GAN(discriminator_layers, generator_layers)
gan.train(X, nb_epoch=150, batch_size=5, discriminator_steps=2)

Epoch: 0, discriminator loss: 1.490799903869629, generator loss: 0.4140889048576355
Epoch: 1, discriminator loss: 1.4364362955093384, generator loss: 0.49492472410202026
Epoch: 2, discriminator loss: 1.404874324798584, generator loss: 0.5674110651016235
Epoch: 3, discriminator loss: 1.391737461090088, generator loss: 0.6212331652641296
Epoch: 4, discriminator loss: 1.386643648147583, generator loss: 0.6517943143844604
Epoch: 5, discriminator loss: 1.375281572341919, generator loss: 0.6671280860900879
Epoch: 6, discriminator loss: 1.3614658117294312, generator loss: 0.681520938873291
Epoch: 7, discriminator loss: 1.3589646816253662, generator loss: 0.6202360987663269
Epoch: 8, discriminator loss: 1.4632829427719116, generator loss: 0.6730211973190308
Epoch: 9, discriminator loss: 1.4941837787628174, generator loss: 0.7115226984024048
Epoch: 10, discriminator loss: 1.4735699892044067, generator loss: 0.626997709274292
Epoch: 11, discriminator loss: 1.3734543323516846, generator loss: 0.6

In [4]:
gan.generate_samples(10)

array([[ 0.82286429,  0.06186615,  0.35310692,  0.99341476],
       [ 0.03446291,  0.94318295,  0.12055588,  0.00606388],
       [ 0.62049049,  0.19632798,  0.24209307,  0.9075613 ],
       [ 0.05745903,  0.88128054,  0.11820747,  0.02301324],
       [ 0.78784901,  0.0684895 ,  0.33140084,  0.991521  ],
       [ 0.22671881,  0.37728301,  0.15340915,  0.4068011 ],
       [ 0.09689891,  0.75855774,  0.14134948,  0.09562992],
       [ 0.02882782,  0.88491029,  0.07493525,  0.00802684],
       [ 0.45593026,  0.1402266 ,  0.24176201,  0.88480145],
       [ 0.31504497,  0.19276431,  0.19334783,  0.76300633]], dtype=float32)

In [5]:
discriminator_layers=[(7, None), (6, tf.nn.tanh), (3, tf.nn.softmax), (1, None)]
generator_layers=[(9, None), (5, tf.nn.tanh), (4, None)]
cgan = CGAN(discriminator_layers, generator_layers)
cgan.train(X, y, nb_epoch=150, batch_size=5, discriminator_steps=1)

Epoch: 0, discriminator loss: 1.6523098945617676, generator loss: 0.29970329999923706
Epoch: 1, discriminator loss: 1.5994004011154175, generator loss: 0.3310699164867401
Epoch: 2, discriminator loss: 1.550580382347107, generator loss: 0.3658149242401123
Epoch: 3, discriminator loss: 1.5104293823242188, generator loss: 0.4001856744289398
Epoch: 4, discriminator loss: 1.4795063734054565, generator loss: 0.4332950711250305
Epoch: 5, discriminator loss: 1.4556725025177002, generator loss: 0.46100449562072754
Epoch: 6, discriminator loss: 1.4411755800247192, generator loss: 0.48999032378196716
Epoch: 7, discriminator loss: 1.426853895187378, generator loss: 0.5139530897140503
Epoch: 8, discriminator loss: 1.416275978088379, generator loss: 0.5410186648368835
Epoch: 9, discriminator loss: 1.409661889076233, generator loss: 0.5602079629898071
Epoch: 10, discriminator loss: 1.4035042524337769, generator loss: 0.5811821222305298
Epoch: 11, discriminator loss: 1.397782564163208, generator loss:

In [59]:
cgan.generate_samples(10, 1)

array([[ 0.1427446 ,  0.25820407,  0.71241528,  0.80112904],
       [ 0.58134753,  0.64160776,  0.79944354,  0.85646617],
       [ 0.92438316,  0.83942538,  0.92529041,  0.93354577],
       [ 0.0405555 ,  0.12971404,  0.54324424,  0.62391841],
       [ 0.8086018 ,  0.80916679,  0.84699678,  0.89936841],
       [ 0.07473692,  0.1681546 ,  0.6725744 ,  0.77329409],
       [ 0.02196066,  0.11114164,  0.32455224,  0.36907181],
       [ 0.12258787,  0.23161577,  0.6954993 ,  0.78482884],
       [ 0.06398835,  0.14856528,  0.61575019,  0.70132172],
       [ 0.09529524,  0.19102204,  0.65368778,  0.73630053]], dtype=float32)

In [58]:
X[ds.target == 1]

array([[ 0.75      ,  0.5       ,  0.62711864,  0.54166667],
       [ 0.58333333,  0.5       ,  0.59322034,  0.58333333],
       [ 0.72222222,  0.45833333,  0.66101695,  0.58333333],
       [ 0.33333333,  0.125     ,  0.50847458,  0.5       ],
       [ 0.61111111,  0.33333333,  0.61016949,  0.58333333],
       [ 0.38888889,  0.33333333,  0.59322034,  0.5       ],
       [ 0.55555556,  0.54166667,  0.62711864,  0.625     ],
       [ 0.16666667,  0.16666667,  0.38983051,  0.375     ],
       [ 0.63888889,  0.375     ,  0.61016949,  0.5       ],
       [ 0.25      ,  0.29166667,  0.49152542,  0.54166667],
       [ 0.19444444,  0.        ,  0.42372881,  0.375     ],
       [ 0.44444444,  0.41666667,  0.54237288,  0.58333333],
       [ 0.47222222,  0.08333333,  0.50847458,  0.375     ],
       [ 0.5       ,  0.375     ,  0.62711864,  0.54166667],
       [ 0.36111111,  0.375     ,  0.44067797,  0.5       ],
       [ 0.66666667,  0.45833333,  0.57627119,  0.54166667],
       [ 0.36111111,  0.